import json
from pprint import pprint

from django.http import JsonResponse
from django.shortcuts import render


# Create your views here.

def check_credit(request):
    data = """{
          "root":{
          "listRecord":{
          "list":[
          { "year_smt":"2017\/2학기", "year_smt_cd":"201720", "curi_class":"003284-003", "year":"2017", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"003284", "class":"003", "student_no":"121693", "curi_nm":"컴퓨터네트워크", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"001", "domain_cd_nm":"기본이수", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"", "mrks":"", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/2학기", "year_smt_cd":"201720", "curi_class":"005617-001", "year":"2017", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"005617", "class":"001", "student_no":"121693", "curi_nm":"Unix프로그래밍", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"", "mrks":"", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/2학기", "year_smt_cd":"201720", "curi_class":"009954-002", "year":"2017", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"009954", "class":"002", "student_no":"121693", "curi_nm":"알고리즘및실습", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"4.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"", "mrks":"", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"004118-004", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"004118", "class":"004", "student_no":"121693", "curi_nm":"디지털시스템", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"004310-003", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"004310", "class":"003", "student_no":"121693", "curi_nm":"운영체제", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"005623-001", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"005623", "class":"001", "student_no":"121693", "curi_nm":"분자유전학", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3125", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"006139-001", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"006139", "class":"001", "student_no":"121693", "curi_nm":"임베디드시스템", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"007219-003", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"007219", "class":"003", "student_no":"121693", "curi_nm":"데이터베이스", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"009030-018", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"009030", "class":"018", "student_no":"121693", "curi_nm":"취업역량개발론", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"18", "slt_domain_cd_nm":"역량강화", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2017\/1학기", "year_smt_cd":"2017\/10", "curi_class":"009952-004", "year":"2017", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"009952", "class":"004", "student_no":"121693", "curi_nm":"자료구조및실습", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"4.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/겨울학기", "year_smt_cd":"2016\/21", "curi_class":"008071-001", "year":"2016", "smt_cd":"21", "smt_cd_nm":"겨울학기", "orgn_clsf_cd":"20", "curi_no":"008071", "class":"001", "student_no":"121693", "curi_nm":"객체지향설계기술", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"003276-005", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"003276", "class":"005", "student_no":"121693", "curi_nm":"컴퓨터구조론", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"005130-004", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"005130", "class":"004", "student_no":"121693", "curi_nm":"JAVA프로그래밍", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"008364-023", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"008364", "class":"023", "student_no":"121693", "curi_nm":"세종사회봉사1", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"17", "slt_domain_cd_nm":"인성과창의력", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"2012-1 [008364] 세종사회봉사1(학부)", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"2012", "re_smt_cd":"10", "re_orgn_clsf_cd":"20", "re_curi_no":"008364", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"008366-001", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"008366", "class":"001", "student_no":"121693", "curi_nm":"고전독서1", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"009913-003", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"009913", "class":"003", "student_no":"121693", "curi_nm":"고급C프로그래밍및실습", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"4.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"009914-003", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"009914", "class":"003", "student_no":"121693", "curi_nm":"공학설계기초(산학프로젝트입문)", "curi_type_cd":"52", "curi_type_cd_nm":"복선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/2학기", "year_smt_cd":"2016\/20", "curi_class":"009936-001", "year":"2016", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"009936", "class":"001", "student_no":"121693", "curi_nm":"Technical Writing기초", "curi_type_cd":"18", "curi_type_cd_nm":"중선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"23", "slt_domain_cd_nm":"세계와지구촌", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"C+", "mrks":"2.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"005211-001", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"005211", "class":"001", "student_no":"121693", "curi_nm":"생물화학공학", "curi_type_cd":"21", "curi_type_cd_nm":"전필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3113", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"005212-001", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"005212", "class":"001", "student_no":"121693", "curi_nm":"세포생물학1", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3125", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"007818-003", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"007818", "class":"003", "student_no":"121693", "curi_nm":"분자생물학1및실험", "curi_type_cd":"21", "curi_type_cd_nm":"전필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3125", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"008304-001", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"008304", "class":"001", "student_no":"121693", "curi_nm":"English Composition 2", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"2012-2 [008304] English Composition 2(학부)", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"2012", "re_smt_cd":"20", "re_orgn_clsf_cd":"20", "re_curi_no":"008304", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"009687-001", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"009687", "class":"001", "student_no":"121693", "curi_nm":"인지뇌과학", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3113", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2016\/1학기", "year_smt_cd":"2016\/10", "curi_class":"009912-004", "year":"2016", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"009912", "class":"004", "student_no":"121693", "curi_nm":"C프로그래밍및실습", "curi_type_cd":"51", "curi_type_cd_nm":"복필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"4.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A+", "mrks":"4.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"2922", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"001468-001", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"001468", "class":"001", "student_no":"121693", "curi_nm":"분석화학", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3111", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"002723-002", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"002723", "class":"002", "student_no":"121693", "curi_nm":"일반화학및실험2", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"2012-2 [002723] 일반화학및실험2(학부)", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"2012", "re_smt_cd":"20", "re_orgn_clsf_cd":"20", "re_curi_no":"002723", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"007326-026", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"007326", "class":"026", "student_no":"121693", "curi_nm":"미적분학및연습2", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"2012-2 [007326] 미적분학및연습2(학부)", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"2012", "re_smt_cd":"20", "re_orgn_clsf_cd":"20", "re_curi_no":"007326", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"007500-002", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"007500", "class":"002", "student_no":"121693", "curi_nm":"생물통계학", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"007504-003", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"007504", "class":"003", "student_no":"121693", "curi_nm":"영어듣기연습", "curi_type_cd":"19", "curi_type_cd_nm":"자교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"15", "slt_domain_cd_nm":"지구촌의이해", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"007752-002", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"007752", "class":"002", "student_no":"121693", "curi_nm":"생명화학2및실험", "curi_type_cd":"21", "curi_type_cd_nm":"전필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3111", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"008306-054", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"008306", "class":"054", "student_no":"121693", "curi_nm":"English Composition 4", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/2학기", "year_smt_cd":"2013\/20", "curi_class":"009045-001", "year":"2013", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"009045", "class":"001", "student_no":"121693", "curi_nm":"창업과기업가정신1", "curi_type_cd":"18", "curi_type_cd_nm":"중선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"21", "slt_domain_cd_nm":"융합과창업", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"004281-002", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"004281", "class":"002", "student_no":"121693", "curi_nm":"유기화학", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3111", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"004751-001", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"004751", "class":"001", "student_no":"121693", "curi_nm":"미생물학및실험", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3111", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"005194-002", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"005194", "class":"002", "student_no":"121693", "curi_nm":"생물리화학", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"006919-001", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"006919", "class":"001", "student_no":"121693", "curi_nm":"생명화학1", "curi_type_cd":"22", "curi_type_cd_nm":"전선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3111", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"008305-050", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"008305", "class":"050", "student_no":"121693", "curi_nm":"English Composition 3", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2013\/1학기", "year_smt_cd":"2013\/10", "curi_class":"008891-001", "year":"2013", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"008891", "class":"001", "student_no":"121693", "curi_nm":"인체와생명", "curi_type_cd":"18", "curi_type_cd_nm":"중선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/2학기", "year_smt_cd":"2012\/20", "curi_class":"006936-001", "year":"2012", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"006936", "class":"001", "student_no":"121693", "curi_nm":"일반생물학2", "curi_type_cd":"21", "curi_type_cd_nm":"전필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3110", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/2학기", "year_smt_cd":"2012\/20", "curi_class":"007324-002", "year":"2012", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"007324", "class":"002", "student_no":"121693", "curi_nm":"사회와가치", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/2학기", "year_smt_cd":"2012\/20", "curi_class":"008361-007", "year":"2012", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"008361", "class":"007", "student_no":"121693", "curi_nm":"신입생세미나2", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3110", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/2학기", "year_smt_cd":"2012\/20", "curi_class":"008377-001", "year":"2012", "smt_cd":"20", "smt_cd_nm":"2학기", "orgn_clsf_cd":"20", "curi_no":"008377", "class":"001", "student_no":"121693", "curi_nm":"전산개론-I", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"002719-007", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"002719", "class":"007", "student_no":"121693", "curi_nm":"일반화학및실험1", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"006847-002", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"006847", "class":"002", "student_no":"121693", "curi_nm":"일반생물학1", "curi_type_cd":"21", "curi_type_cd_nm":"전필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"A0", "mrks":"4.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3110", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"007323-003", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"007323", "class":"003", "student_no":"121693", "curi_nm":"쓰기와말하기", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"007325-003", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"007325", "class":"003", "student_no":"121693", "curi_nm":"미적분학및연습1", "curi_type_cd":"1A", "curi_type_cd_nm":"기교", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"13", "slt_domain_cd_nm":"생명과자연", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"007357-001", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"007357", "class":"001", "student_no":"121693", "curi_nm":"생활속의심리학", "curi_type_cd":"18", "curi_type_cd_nm":"중선", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"10", "slt_domain_cd_nm":"인성과도덕", "cdt":"3.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B0", "mrks":"3.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"008303-042", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"008303", "class":"042", "student_no":"121693", "curi_nm":"English Composition 1", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"2.0", "grade_type_cd":"1", "grade_type_cd_nm":"GRADE", "grade":"B+", "mrks":"3.5", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"9001", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""},
          { "year_smt":"2012\/1학기", "year_smt_cd":"2012\/10", "curi_class":"008360-007", "year":"2012", "smt_cd":"10", "smt_cd_nm":"1학기", "orgn_clsf_cd":"20", "curi_no":"008360", "class":"007", "student_no":"121693", "curi_nm":"신입생세미나1", "curi_type_cd":"17", "curi_type_cd_nm":"중필", "domain_cd":"", "domain_cd_nm":"", "slt_domain_cd":"", "slt_domain_cd_nm":"", "cdt":"1.0", "grade_type_cd":"2", "grade_type_cd_nm":"P\/NP", "grade":"P", "mrks":"0.0", "re_info":"", "pref_orgn_clsf_cd":"", "pref_curi_nm":"", "pref_curi_no":"", "gvup_curi_cd":"", "gvup_curi_cd_nm":"", "gvup_smt_cd":"", "gdt_except_cd":"", "gdt_except_cd_nm":"", "out_record_cd":"", "out_record_cd_nm":"", "out_orgn_nm":"", "dept_cd":"3110", "re_year":"", "re_smt_cd":"", "re_orgn_clsf_cd":"", "re_curi_no":"", "gvup_nm":""}
          ]
          },
          "listRecord2":{
          "list":[
          { "cul_cdt":"17", "cul_tot":"45", "maj_cdt":"15", "maj_tot":"24", "boo_cdt":"0", "bok_tot":"36", "edu_tot":"0", "etc_tot":"0", "out_tot":"0", "req_cdt":"130", "app_cdt":"120", "gru_cdt":"120", "tot_mrks":"419", "avg_mrks":"3.71", "curi_limit":"", "base_maj_remark":"0"}
          ]
          }
          }
          }"""

    dict = json.loads(data)

    ### credit ###
    core_essential = float(dict['root']['listRecord2']['list'][0][
                               'cul_cdt'])  # 중핵필수 (EX : English Composition, 쓰기와 말하기, 사회와 가치, 신입생 세미나 등)
    core_essential_selection = 0  # 중핵필수선택 (EX : 정보사회의사이버윤리, 과학사, 세종리더십 등)
    liberal_arts = 0  # 자유교양

    major_basic = 0  # 전공기초교양 (EX : 경영수학, 경영통계학, 공업수학, 고등미적분학 등)
    major_required = float(dict["root"]['listRecord2']['list'][0]['maj_cdt'])  # 전공필수
    major_select = float(dict["root"]['listRecord2']['list'][0]['maj_tot'])  # 전공선택
    major_limit = 15  # 전필제한
    if major_required > major_limit:
        major_select += (major_required - major_limit)
        major_required = major_limit

    sum_of_major = major_required + major_select  # 전공합계

    sum_of_bok_essential = 0  # 복수전공 필수
    sum_of_bok_optional = 0  # 복수전공 선택
    bok_limit = 15  # 복필제한

    sum_of_boo_essential = 0  # 부전공 필수
    sum_of_boo_optional = 0  # 부전공 선택

    sum_of_edu = 0  # 교직
    sum_of_etc = 0  # 기타

    reqeust_credit = 0  # 신청학점
    acquired_credit = float(dict["root"]['listRecord2']['list'][0]['gru_cdt'])  # 취득학점
    total_credit = 0 # 취득학점 + 이번학기 학점
    ### credit ###

    result_graduate = False # 통과 / 불통과

    for i in range(0, len(dict['root']['listRecord']['list'])):
        input_type = dict["root"]['listRecord']['list'][i]['grade']
        input_curi = dict["root"]['listRecord']['list'][i]['curi_type_cd_nm']

        if input_type == "":
            reqeust_credit += float(dict["root"]['listRecord']['list'][i]['cdt'])
            print("AAAAAAA")

        if input_curi == "중선":
            core_essential_selection += float(dict["root"]['listRecord']['list'][i]['cdt'])

        elif input_curi == "기교":
            major_basic += float((dict['root']['listRecord']['list'][i]['cdt']))

        elif input_curi == "자교":
            liberal_arts += float((dict['root']['listRecord']['list'][i]['cdt']))

        elif input_curi == "복필":
            if sum_of_bok_essential > bok_limit:
                sum_of_bok_optional += float(dict['root']['listRecord']['list'][i]['cdt'])
                sum_of_bok_essential = bok_limit
            else:
                sum_of_bok_essential += float(dict['root']['listRecord']['list'][i]['cdt'])

        elif input_curi == "복선":
            sum_of_bok_optional += float(dict['root']['listRecord']['list'][i]['cdt'])

        elif input_curi == "부필":
            sum_of_boo_essential += float(dict['root']['listRecord']['list'][i]['cdt'])

        elif input_curi == "부선":
            sum_of_boo_optional += float(dict['root']['listRecord']['list'][i]['cdt'])

        elif input_curi == "교육":
            sum_of_edu += float(dict['root']['listRecord']['list'][i]['cdt'])

        elif input_curi == "기타":
            sum_of_etc += float(dict['root']['listRecord']['list'][i]['cdt'])

        total_credit = reqeust_credit + acquired_credit

        list_credits = [core_essential, core_essential_selection, liberal_arts,
                        major_basic, major_required, major_select, sum_of_major,
                        sum_of_bok_essential, sum_of_bok_optional,
                        sum_of_boo_essential, sum_of_boo_optional,
                        sum_of_edu, sum_of_etc,
                        reqeust_credit, acquired_credit, total_credit]

    result_graduate = graduation(list_credits)
    print(result_graduate)
    return JsonResponse(
        {"credit": {
            "중필": core_essential,
            "중선": core_essential_selection,
            "자교": liberal_arts,
            "전공기초": major_basic,
            "전공필수": major_required,
            "전공선택": major_select,
            "부전공": (sum_of_boo_essential + sum_of_boo_optional),
            "복수전공": (sum_of_bok_essential + sum_of_bok_optional),
            "교직": sum_of_edu,
            "기타": sum_of_etc,
            "학점통과": result_graduate
        },
            "origin": data
        }
    )


def graduation(list_credits):
    data = """{
                "root":{
                "listEtc":{
                "list":[
                { "maj_yn":"비대상", "early_yn":"비대상", "teh_yn":"비대상", "rotc_yn":"비대상", "etc_yn":"3학점", "div_yn":"대상", "termover_yn":"비대상"}
                ]
                },
                "listMain":{
                "list":[
                { "student_no":"121693", "maj_div_cd":"1", "maj_div_cd_nm":"주전공", "dept_cd":"3111", "sch_dept_alias":"생명공학부 생명공학전공", "exam1":"N\/P", "exam2":"비대상", "exam3":"비대상", "cdt_div":"1", "cdt_div_nm":"기준정보", "r_cul_base_cdt":"0", "r_cul_req_cdt":"0", "r_cul_free_cdt":"0", "r_cul_cdt":"0", "r_maj_base_cdt":"0", "r_maj_req_cdt":"15", "r_maj_cdt":"39", "r_tot_cdt":"130", "avg_mrks":"1.75", "judge_pref":"미정", "rotc":"", "pass_vert":"", "domain_judge":"비대상", "r_cul_cor_cdt":"9", "r_maj_sel_cdt":"24", "r_maj_req_sel_cdt":"39", "slt_domain_judge":"", "notes":"과목이수표 참고"},
                { "student_no":"121693", "maj_div_cd":"1", "maj_div_cd_nm":"주전공", "dept_cd":"3111", "sch_dept_alias":"생명공학부 생명공학전공", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"2", "cdt_div_nm":"기취득", "r_cul_base_cdt":"18", "r_cul_req_cdt":"17", "r_cul_free_cdt":"1", "r_cul_cdt":"45", "r_maj_base_cdt":"0", "r_maj_req_cdt":"15", "r_maj_cdt":"39", "r_tot_cdt":"84", "avg_mrks":"3.71", "judge_pref":"☞과목보기", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"9", "r_maj_sel_cdt":"24", "r_maj_req_sel_cdt":"39", "slt_domain_judge":"", "notes":""},
                { "student_no":"121693", "maj_div_cd":"1", "maj_div_cd_nm":"주전공", "dept_cd":"3111", "sch_dept_alias":"생명공학부 생명공학전공", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"3", "cdt_div_nm":"수강중(재수강)", "r_cul_base_cdt":"0(0)", "r_cul_req_cdt":"0(0)", "r_cul_free_cdt":"0(0)", "r_cul_cdt":"0(0)", "r_maj_base_cdt":"0(0)", "r_maj_req_cdt":"0(0)", "r_maj_cdt":"0(0)", "r_tot_cdt":"0(0)", "avg_mrks":"평가전", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"0(0)", "r_maj_sel_cdt":"0(0)", "r_maj_req_sel_cdt":"0", "slt_domain_judge":"", "notes":""},
                { "student_no":"121693", "maj_div_cd":"1", "maj_div_cd_nm":"주전공", "dept_cd":"3111", "sch_dept_alias":"생명공학부 생명공학전공", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"4", "cdt_div_nm":"취득예상", "r_cul_base_cdt":"18", "r_cul_req_cdt":"17", "r_cul_free_cdt":"1", "r_cul_cdt":"45", "r_maj_base_cdt":"0", "r_maj_req_cdt":"15", "r_maj_cdt":"39", "r_tot_cdt":"84", "avg_mrks":"3.71", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"9", "r_maj_sel_cdt":"24", "r_maj_req_sel_cdt":"39", "slt_domain_judge":"", "notes":""},
                { "student_no":"121693", "maj_div_cd":"3", "maj_div_cd_nm":"복수전공", "dept_cd":"2922", "sch_dept_alias":"컴퓨터공학과", "exam1":"비대상", "exam2":"비대상", "exam3":"비대상", "cdt_div":"1", "cdt_div_nm":"기준정보", "r_cul_base_cdt":"0", "r_cul_req_cdt":"0", "r_cul_free_cdt":"0", "r_cul_cdt":"0", "r_maj_base_cdt":"0", "r_maj_req_cdt":"15", "r_maj_cdt":"0", "r_tot_cdt":"39", "avg_mrks":"", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"비대상", "r_cul_cor_cdt":"0", "r_maj_sel_cdt":"24", "r_maj_req_sel_cdt":"39", "slt_domain_judge":"", "notes":"과목이수표 참고"},
                { "student_no":"121693", "maj_div_cd":"3", "maj_div_cd_nm":"복수전공", "dept_cd":"2922", "sch_dept_alias":"컴퓨터공학과", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"2", "cdt_div_nm":"기취득", "r_cul_base_cdt":"0", "r_cul_req_cdt":"0", "r_cul_free_cdt":"0", "r_cul_cdt":"0", "r_maj_base_cdt":"0", "r_maj_req_cdt":"15", "r_maj_cdt":"36", "r_tot_cdt":"36", "avg_mrks":"", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"0", "r_maj_sel_cdt":"21", "r_maj_req_sel_cdt":"36", "slt_domain_judge":"", "notes":""},
                { "student_no":"121693", "maj_div_cd":"3", "maj_div_cd_nm":"복수전공", "dept_cd":"2922", "sch_dept_alias":"컴퓨터공학과", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"3", "cdt_div_nm":"수강중(재수강)", "r_cul_base_cdt":"0(0)", "r_cul_req_cdt":"0(0)", "r_cul_free_cdt":"0(0)", "r_cul_cdt":"0(0)", "r_maj_base_cdt":"0(0)", "r_maj_req_cdt":"7(0)", "r_maj_cdt":"10(0)", "r_tot_cdt":"0(0)", "avg_mrks":"", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"0(0)", "r_maj_sel_cdt":"3(0)", "r_maj_req_sel_cdt":"10", "slt_domain_judge":"", "notes":""},
                { "student_no":"121693", "maj_div_cd":"3", "maj_div_cd_nm":"복수전공", "dept_cd":"2922", "sch_dept_alias":"컴퓨터공학과", "exam1":"", "exam2":"", "exam3":"", "cdt_div":"4", "cdt_div_nm":"취득예상", "r_cul_base_cdt":"0", "r_cul_req_cdt":"0", "r_cul_free_cdt":"0", "r_cul_cdt":"0", "r_maj_base_cdt":"0", "r_maj_req_cdt":"22", "r_maj_cdt":"46", "r_tot_cdt":"36", "avg_mrks":"", "judge_pref":"", "rotc":"", "pass_vert":"", "domain_judge":"", "r_cul_cor_cdt":"0", "r_maj_sel_cdt":"24", "r_maj_req_sel_cdt":"46", "slt_domain_judge":"", "notes":""}
                ]
                },
                "strJudgePass":""
                }
                }"""

    dict = json.loads(data)

    standard_major_essential = 21.0
    standard_major_sum = 42.0
    standard_bok_essential = 15.0
    standard_bok_sum = 39.0
    standard_boo = 21.0

    if list_credits[15] >= 130.0:  # 총 학점 비교
        if (list_credits[0] >= 15.0) and (list_credits[1] >= 9.0):  # 중핵, 중선 비교
            if dict['root']['listEtc']['list'][0]['div_yn'] == "비대상":  # 단일전공
                if (list_credits[4] == standard_major_essential) and (list_credits[6] >= standard_major_sum):  # 전필, 전공합계 비교
                    return True
            else:  # 복수/부 전공
                if (list_credits[4] == standard_bok_essential) and (list_credits[6] >= standard_bok_sum) and (((list_credits[7] >= standard_bok_essential) and ((list_credits[7] + list_credits[8]) >= standard_bok_sum)) or ((list_credits[9] + list_credits[10]) >= standard_boo)):
                    return True

    return False


